# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import base_pb2 as base__pb2
from exam import exam_base_pb2 as exam_dot_exam__base__pb2


class ExamBaseStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListVersions = channel.unary_unary(
        '/exam_base.ExamBase/ListVersions',
        request_serializer=base__pb2.Empty.SerializeToString,
        response_deserializer=exam_dot_exam__base__pb2.ListVersionsRes.FromString,
        )
    self.CreateOrUpdateVersion = channel.unary_unary(
        '/exam_base.ExamBase/CreateOrUpdateVersion',
        request_serializer=exam_dot_exam__base__pb2.Version.SerializeToString,
        response_deserializer=exam_dot_exam__base__pb2.Version.FromString,
        )
    self.CheckVersion = channel.unary_unary(
        '/exam_base.ExamBase/CheckVersion',
        request_serializer=exam_dot_exam__base__pb2.Version.SerializeToString,
        response_deserializer=exam_dot_exam__base__pb2.CheckVersionRes.FromString,
        )


class ExamBaseServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListVersions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateOrUpdateVersion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckVersion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExamBaseServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListVersions': grpc.unary_unary_rpc_method_handler(
          servicer.ListVersions,
          request_deserializer=base__pb2.Empty.FromString,
          response_serializer=exam_dot_exam__base__pb2.ListVersionsRes.SerializeToString,
      ),
      'CreateOrUpdateVersion': grpc.unary_unary_rpc_method_handler(
          servicer.CreateOrUpdateVersion,
          request_deserializer=exam_dot_exam__base__pb2.Version.FromString,
          response_serializer=exam_dot_exam__base__pb2.Version.SerializeToString,
      ),
      'CheckVersion': grpc.unary_unary_rpc_method_handler(
          servicer.CheckVersion,
          request_deserializer=exam_dot_exam__base__pb2.Version.FromString,
          response_serializer=exam_dot_exam__base__pb2.CheckVersionRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'exam_base.ExamBase', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
