# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import base_pb2 as base__pb2
from exam import preview_score_pb2 as exam_dot_preview__score__pb2


class PreviewScoreStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ClientRegisterOrUpdateExamInfo = channel.unary_unary(
        '/preview_score.PreviewScore/ClientRegisterOrUpdateExamInfo',
        request_serializer=exam_dot_preview__score__pb2.ClientExamInfo.SerializeToString,
        response_deserializer=exam_dot_preview__score__pb2.ClientUserInfoRes.FromString,
        )
    self.ClientUserInfo = channel.unary_unary(
        '/preview_score.PreviewScore/ClientUserInfo',
        request_serializer=base__pb2.IdReq.SerializeToString,
        response_deserializer=exam_dot_preview__score__pb2.ClientUserInfoRes.FromString,
        )
    self.ClientRealtimePreviewAvailablity = channel.unary_unary(
        '/preview_score.PreviewScore/ClientRealtimePreviewAvailablity',
        request_serializer=base__pb2.Empty.SerializeToString,
        response_deserializer=exam_dot_preview__score__pb2.RealtimePreviewAvailablity.FromString,
        )
    self.ClientRegisteredUserNums = channel.unary_unary(
        '/preview_score.PreviewScore/ClientRegisteredUserNums',
        request_serializer=base__pb2.Empty.SerializeToString,
        response_deserializer=exam_dot_preview__score__pb2.ClientRegisteredUserNumsRes.FromString,
        )
    self.ClientFormIdCollect = channel.unary_unary(
        '/preview_score.PreviewScore/ClientFormIdCollect',
        request_serializer=exam_dot_preview__score__pb2.ClientFormIdCollectReq.SerializeToString,
        response_deserializer=base__pb2.DefaultRes.FromString,
        )
    self.ClientShareInfoGet = channel.unary_unary(
        '/preview_score.PreviewScore/ClientShareInfoGet',
        request_serializer=base__pb2.Empty.SerializeToString,
        response_deserializer=exam_dot_preview__score__pb2.ClientShareInfo.FromString,
        )
    self.WechatFollowCallback = channel.unary_unary(
        '/preview_score.PreviewScore/WechatFollowCallback',
        request_serializer=exam_dot_preview__score__pb2.WechatFollowCallbackReq.SerializeToString,
        response_deserializer=base__pb2.DefaultRes.FromString,
        )
    self.GetVersionStatus = channel.unary_unary(
        '/preview_score.PreviewScore/GetVersionStatus',
        request_serializer=exam_dot_preview__score__pb2.GetVersionStatusReq.SerializeToString,
        response_deserializer=exam_dot_preview__score__pb2.GetVersionStatusRes.FromString,
        )
    self.ClientOpenIdCollect = channel.unary_unary(
        '/preview_score.PreviewScore/ClientOpenIdCollect',
        request_serializer=exam_dot_preview__score__pb2.ClientOpenIdCollectReq.SerializeToString,
        response_deserializer=base__pb2.DefaultRes.FromString,
        )
    self.QueryScore = channel.unary_unary(
        '/preview_score.PreviewScore/QueryScore',
        request_serializer=exam_dot_preview__score__pb2.QueryScoreReq.SerializeToString,
        response_deserializer=exam_dot_preview__score__pb2.QueryScoreRes.FromString,
        )


class PreviewScoreServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ClientRegisterOrUpdateExamInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClientUserInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClientRealtimePreviewAvailablity(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClientRegisteredUserNums(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClientFormIdCollect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClientShareInfoGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WechatFollowCallback(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVersionStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClientOpenIdCollect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def QueryScore(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PreviewScoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ClientRegisterOrUpdateExamInfo': grpc.unary_unary_rpc_method_handler(
          servicer.ClientRegisterOrUpdateExamInfo,
          request_deserializer=exam_dot_preview__score__pb2.ClientExamInfo.FromString,
          response_serializer=exam_dot_preview__score__pb2.ClientUserInfoRes.SerializeToString,
      ),
      'ClientUserInfo': grpc.unary_unary_rpc_method_handler(
          servicer.ClientUserInfo,
          request_deserializer=base__pb2.IdReq.FromString,
          response_serializer=exam_dot_preview__score__pb2.ClientUserInfoRes.SerializeToString,
      ),
      'ClientRealtimePreviewAvailablity': grpc.unary_unary_rpc_method_handler(
          servicer.ClientRealtimePreviewAvailablity,
          request_deserializer=base__pb2.Empty.FromString,
          response_serializer=exam_dot_preview__score__pb2.RealtimePreviewAvailablity.SerializeToString,
      ),
      'ClientRegisteredUserNums': grpc.unary_unary_rpc_method_handler(
          servicer.ClientRegisteredUserNums,
          request_deserializer=base__pb2.Empty.FromString,
          response_serializer=exam_dot_preview__score__pb2.ClientRegisteredUserNumsRes.SerializeToString,
      ),
      'ClientFormIdCollect': grpc.unary_unary_rpc_method_handler(
          servicer.ClientFormIdCollect,
          request_deserializer=exam_dot_preview__score__pb2.ClientFormIdCollectReq.FromString,
          response_serializer=base__pb2.DefaultRes.SerializeToString,
      ),
      'ClientShareInfoGet': grpc.unary_unary_rpc_method_handler(
          servicer.ClientShareInfoGet,
          request_deserializer=base__pb2.Empty.FromString,
          response_serializer=exam_dot_preview__score__pb2.ClientShareInfo.SerializeToString,
      ),
      'WechatFollowCallback': grpc.unary_unary_rpc_method_handler(
          servicer.WechatFollowCallback,
          request_deserializer=exam_dot_preview__score__pb2.WechatFollowCallbackReq.FromString,
          response_serializer=base__pb2.DefaultRes.SerializeToString,
      ),
      'GetVersionStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetVersionStatus,
          request_deserializer=exam_dot_preview__score__pb2.GetVersionStatusReq.FromString,
          response_serializer=exam_dot_preview__score__pb2.GetVersionStatusRes.SerializeToString,
      ),
      'ClientOpenIdCollect': grpc.unary_unary_rpc_method_handler(
          servicer.ClientOpenIdCollect,
          request_deserializer=exam_dot_preview__score__pb2.ClientOpenIdCollectReq.FromString,
          response_serializer=base__pb2.DefaultRes.SerializeToString,
      ),
      'QueryScore': grpc.unary_unary_rpc_method_handler(
          servicer.QueryScore,
          request_deserializer=exam_dot_preview__score__pb2.QueryScoreReq.FromString,
          response_serializer=exam_dot_preview__score__pb2.QueryScoreRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'preview_score.PreviewScore', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
